Entrer le style de texte ou [?] <SURF> : surf
Spécifiez le point de départ du texte ou [Justifier/Style] : j
Entrez une option [Aligner/AJuster/Centre/Milieu/Gauche/Droite/HG/HC/HD/MG/MC/MD/BG/BC/BD] : MC
Spécifier le point milieu-centre du texte : 
Spécifier la hauteur de texte <0.1500> : 0.150000000000000
Spécifiez l'angle de rotation du texte <260.00> : 100
Texte : 12.3 m²
Commande : -layer
Calque courant : GEX_EDS_sdp_2-tremie_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : E
Entrer le nom du nouveau calque courant : 0
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : g
Entrer le nom de la liste de calque(s) à Geler ou <sélectionner les objets> : *
Impossible de geler le calque "0" car c'est le calque courant. Veuillez spécifier un autre calque.
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_3-h-180
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_3-h-180_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : 
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : p
Entrez un nom de motif [? liste/Solid/défini par l'Utilisateur] <SOLID> : s
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : a
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : s
Recréer les contours ? [Oui/Non] <Non> : n
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : a
Associativité des hachures ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : i
Voulez-vous détecter les îlots ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : h
Créer des hachures séparées ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : 
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"0"> : GEX_EDS_sdp_3-h-180
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : s
Choix des objets : 
1 trouvé(s)
Choix des objets : 
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"GEX_EDS_sdp_3-h-180"> : GEX_EDS_sdp_3-h-180_su
Commande : GEX_EDS_sdp_3-h-180
_draworder
Sélectionnez des entités pour changer l'ordre : p
1 trouvé(s)
Sélectionnez des entités pour changer l'ordre : 
Entrer une option [au Dessus des entités/en dEssous des entités/AVant/ARrière] <ARrière> : _back
Commande : _area
Spécifiez le premier point ou [Objet/Ajouter/Soustraire] <Objet> : _o
Sélectionner des objets pour calculer l'aire : 
Aire = 3.7879, Périmètre = 9.7173
Commande : <ENTITY NAME: ee4c1450> entity name  
-EDITHACH
Sélectionnez la hachure : 
Entrez une option 
[DIssociée/Style/Propriétés/ORrdre/AJouter des contours/suppRimer des contours/recréer des Contours/ASsociative/Hachures séparées/Origine/ANnotatif/COuleur des hachures/CAlque/Transparence] <Propriétés> : c
Entrez le type de contour [Région/Polyligne] <Polyligne> : r
Réassocier une hachure avec un nouveau contour ? [Oui/Non] <N> : o
1 région a été créée.
Commande : 
Object Name: AcDbRegion(13.4063 22.8418 0.0)
Region Centroid: (13.4063 22.8418)(13.4063 22.8418 0.0)_TEXT
Style de texte courant : "SURF"  Hauteur du texte : 0.1500 Annotatif : Non
Spécifiez le point de départ du texte ou [Justifier/Style] : S
Entrer le style de texte ou [?] <SURF> : surf
Spécifiez le point de départ du texte ou [Justifier/Style] : j
Entrez une option [Aligner/AJuster/Centre/Milieu/Gauche/Droite/HG/HC/HD/MG/MC/MD/BG/BC/BD] : MC
Spécifier le point milieu-centre du texte : 
Spécifier la hauteur de texte <0.1500> : 0.150000000000000
Spécifiez l'angle de rotation du texte <260.00> : 100
Texte : 3.8 m²
Commande : -layer
Calque courant : GEX_EDS_sdp_3-h-180_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : E
Entrer le nom du nouveau calque courant : 0
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : g
Entrer le nom de la liste de calque(s) à Geler ou <sélectionner les objets> : *
Impossible de geler le calque "0" car c'est le calque courant. Veuillez spécifier un autre calque.
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_5-PK
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_5-PK_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : 
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : p
Entrez un nom de motif [? liste/Solid/défini par l'Utilisateur] <SOLID> : s
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : a
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : s
Recréer les contours ? [Oui/Non] <Non> : n
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : a
Associativité des hachures ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : i
Voulez-vous détecter les îlots ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : h
Créer des hachures séparées ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : 
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"0"> : GEX_EDS_sdp_5-PK
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : s
Choix des objets : 
Commande : 
Commande : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"GEX_EDS_sdp_5-pk"> : GEX_EDS_sdp_5-PK_su
Commande : GEX_EDS_sdp_5-PK
_draworder
Sélectionnez des entités pour changer l'ordre : p
1 trouvé(s)
Sélectionnez des entités pour changer l'ordre : 
Entrer une option [au Dessus des entités/en dEssous des entités/AVant/ARrière] <ARrière> : _back
Commande : -layer
Calque courant : GEX_EDS_sdp_5-pk_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : E
Entrer le nom du nouveau calque courant : 0
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : g
Entrer le nom de la liste de calque(s) à Geler ou <sélectionner les objets> : *
Impossible de geler le calque "0" car c'est le calque courant. Veuillez spécifier un autre calque.
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_6-combles
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_6-combles_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : 
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : p
Entrez un nom de motif [? liste/Solid/défini par l'Utilisateur] <SOLID> : s
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : a
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : s
Recréer les contours ? [Oui/Non] <Non> : n
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : a
Associativité des hachures ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : i
Voulez-vous détecter les îlots ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : h
Créer des hachures séparées ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : 
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"0"> : GEX_EDS_sdp_6-combles
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : s
Choix des objets : 
Commande : 
Commande : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"GEX_EDS_sdp_6-combles"> : GEX_EDS_sdp_6-combles_su
Commande : GEX_EDS_sdp_6-combles
_draworder
Sélectionnez des entités pour changer l'ordre : p
1 trouvé(s)
Sélectionnez des entités pour changer l'ordre : 
Entrer une option [au Dessus des entités/en dEssous des entités/AVant/ARrière] <ARrière> : _back
Commande : -layer
Calque courant : GEX_EDS_sdp_6-combles_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : E
Entrer le nom du nouveau calque courant : 0
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : g
Entrer le nom de la liste de calque(s) à Geler ou <sélectionner les objets> : *
Impossible de geler le calque "0" car c'est le calque courant. Veuillez spécifier un autre calque.
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_7-LT
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_7-LT_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : 
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : p
Entrez un nom de motif [? liste/Solid/défini par l'Utilisateur] <SOLID> : s
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : a
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : s
Recréer les contours ? [Oui/Non] <Non> : n
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : a
Associativité des hachures ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : i
Voulez-vous détecter les îlots ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : h
Créer des hachures séparées ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : 
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"0"> : GEX_EDS_sdp_7-LT
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : s
Choix des objets : 
2 trouvé(s)
Choix des objets : 
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"GEX_EDS_sdp_7-lt"> : GEX_EDS_sdp_7-LT_su
Commande : GEX_EDS_sdp_7-LT
_draworder
Sélectionnez des entités pour changer l'ordre : p
2 trouvé(s)
Sélectionnez des entités pour changer l'ordre : 
Entrer une option [au Dessus des entités/en dEssous des entités/AVant/ARrière] <ARrière> : _back
Commande : _area
Spécifiez le premier point ou [Objet/Ajouter/Soustraire] <Objet> : _o
Sélectionner des objets pour calculer l'aire : 
Aire = 6.2100, Périmètre = 13.3582
Commande : <ENTITY NAME: ee4c16a8> entity name  
-EDITHACH
Sélectionnez la hachure : 
Entrez une option 
[DIssociée/Style/Propriétés/ORrdre/AJouter des contours/suppRimer des contours/recréer des Contours/ASsociative/Hachures séparées/Origine/ANnotatif/COuleur des hachures/CAlque/Transparence] <Propriétés> : c
Entrez le type de contour [Région/Polyligne] <Polyligne> : r
Réassocier une hachure avec un nouveau contour ? [Oui/Non] <N> : o
1 région a été créée.
Commande : 
Object Name: AcDbRegion(-20.5627 29.7919 0.0)
Region Centroid: (-20.5627 29.7919)(-20.5627 29.7919 0.0)_TEXT
Style de texte courant : "SURF"  Hauteur du texte : 0.1500 Annotatif : Non
Spécifiez le point de départ du texte ou [Justifier/Style] : S
Entrer le style de texte ou [?] <SURF> : surf
Spécifiez le point de départ du texte ou [Justifier/Style] : j
Entrez une option [Aligner/AJuster/Centre/Milieu/Gauche/Droite/HG/HC/HD/MG/MC/MD/BG/BC/BD] : MC
Spécifier le point milieu-centre du texte : 
Spécifier la hauteur de texte <0.1500> : 0.150000000000000
Spécifiez l'angle de rotation du texte <260.00> : 100
Texte : 6.2 m²
Commande : _area
Spécifiez le premier point ou [Objet/Ajouter/Soustraire] <Objet> : _o
Sélectionner des objets pour calculer l'aire : 
Aire = 9.9340, Périmètre = 12.7376
Commande : <ENTITY NAME: ee4c1690> entity name  
-EDITHACH
Sélectionnez la hachure : 
Entrez une option 
[DIssociée/Style/Propriétés/ORrdre/AJouter des contours/suppRimer des contours/recréer des Contours/ASsociative/Hachures séparées/Origine/ANnotatif/COuleur des hachures/CAlque/Transparence] <Propriétés> : c
Entrez le type de contour [Région/Polyligne] <Polyligne> : r
Réassocier une hachure avec un nouveau contour ? [Oui/Non] <N> : o
1 région a été créée.
Commande : 
Object Name: AcDbRegion(27.9903 44.6298 0.0)
Region Centroid: (27.9903 44.6298)(27.9903 44.6298 0.0)_TEXT
Style de texte courant : "SURF"  Hauteur du texte : 0.1500 Annotatif : Non
Spécifiez le point de départ du texte ou [Justifier/Style] : S
Entrer le style de texte ou [?] <SURF> : surf
Spécifiez le point de départ du texte ou [Justifier/Style] : j
Entrez une option [Aligner/AJuster/Centre/Milieu/Gauche/Droite/HG/HC/HD/MG/MC/MD/BG/BC/BD] : MC
Spécifier le point milieu-centre du texte : 
Spécifier la hauteur de texte <0.1500> : 0.150000000000000
Spécifiez l'angle de rotation du texte <260.00> : 100
Texte : 9.9 m²
Commande : -layer
Calque courant : GEX_EDS_sdp_7-lt_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : E
Entrer le nom du nouveau calque courant : 0
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : g
Entrer le nom de la liste de calque(s) à Geler ou <sélectionner les objets> : *
Impossible de geler le calque "0" car c'est le calque courant. Veuillez spécifier un autre calque.
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_8-cave
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : GEX_EDS_sdp_8-cave_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : 
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : p
Entrez un nom de motif [? liste/Solid/défini par l'Utilisateur] <SOLID> : s
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : a
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : s
Recréer les contours ? [Oui/Non] <Non> : n
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : a
Associativité des hachures ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : i
Voulez-vous détecter les îlots ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : h
Créer des hachures séparées ? [Oui/Non] <Oui> : o
Entrez une option [jeu de Contours/conServer contour/détection Ilots/stYle/Associativité/Tolérance d'espaces/Hachures séparées] : 
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"0"> : GEX_EDS_sdp_8-cave
Commande : -hachures
Motif de hachure courant : SOLID
Spécifier un point interne ou [Propriétés/Selectionnez objets/Dessiner contour/retirer Contour/Advancé/ORdre affichage/Origine/ANnotatif/couleur des Hachures/CAlque/Transparence] : s
Choix des objets : 
Commande : 
Commande : 
Commande : _clayer
Entrez une nouvelle valeur pour CLAYER <"GEX_EDS_sdp_8-cave"> : GEX_EDS_sdp_8-cave_su
Commande : GEX_EDS_sdp_8-cave
_draworder
Sélectionnez des entités pour changer l'ordre : p
2 trouvé(s)
Sélectionnez des entités pour changer l'ordre : 
Entrer une option [au Dessus des entités/en dEssous des entités/AVant/ARrière] <ARrière> : _back
Commande : -layer
Calque courant : GEX_EDS_sdp_8-cave_su
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : l
Entrer le nom de la liste de calque(s) à Libérer : *
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : E
Entrer le nom du nouveau calque courant : 0
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : g
Entrer le nom de la liste de calque(s) à Geler ou <sélectionner les objets> : GEX_EDS_sdp_teinte_contour
Entrez une option [?/Nouveau/Etablir/CHoisir/COuleur/TLigne/EPaisseur de ligne/Tracer/ACtif/INactif/Geler/Libérer/Verrouiller/Déverrouiller/Renommer/deScription/SUpprimer/étAt/TRANsparence] : 